### ISSUE TITLE
( ͡° ͜ʖ ͡°)

### ISSUE THREAD

**Issue by henrybarreto** [FabricioViannaSM/udemy-javascript#1]
https://github.com/FabricioViannaSM/udemy-javascript/blob/7345bba02e6d65899035f0ef08b0fb2d07a67992/javascript-fabricio-udemy/4_ESTRUTURA_DE_PROGRAMACAO/9_if/script.js#L7

**Comment by gustavosbarreto** [comment]
lá ele infinito

**Comment by luannmoreira** [comment]
> lá ele infinito
`for (;;) {
  console.log("La ele");
}`

**Comment by FabricioViannaSM** [comment]
La ele 1000x
